# Playbook to setup apt repositories and keys.
---
- hosts: localhost
  become: true
  tasks:
    - name: Setup VS Code keys
      apt_key: url=https://packages.microsoft.com/keys/microsoft.asc state=present

    - name: Setup VS Code repos
      apt_repository:
        repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
        state: present
        filename: 'vscode'
        update_cache: 'yes'

    - name: Install VS Code
      apt: name='code' state=present update_cache='yes'
